// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Root from "../Root.mjs";
import * as React from "react";

var renderer = {
  prepare: (function (props) {
      
    }),
  render: (function (props) {
      return React.createElement(Root.make, {});
    })
};

export {
  renderer ,
}
/* Root Not a pure module */
