// Generated by ReScript, PLEASE EDIT WITH CARE


var renderer = {
  prepare: (function (props) {
      
    }),
  render: (function (props) {
      return "A working route";
    })
};

export {
  renderer ,
}
/* No side effect */
