// @generated
// This file is autogenerated, do not edit manually

module Root = {
  module Route = Route__Root_route

}
module DynamicBroken = {
  module Route = Route__DynamicBroken_route

}
module Working = {
  module Route = Route__Working_route

}
module FourOhFour = {
  module Route = Route__FourOhFour_route

}