// Generated by ReScript, PLEASE EDIT WITH CARE


var Root = {
  Route: undefined
};

var DynamicBroken = {
  Route: undefined
};

var Working = {
  Route: undefined
};

var FourOhFour = {
  Route: undefined
};

export {
  Root ,
  DynamicBroken ,
  Working ,
  FourOhFour ,
}
/* No side effect */
