// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_HashMapString from "rescript/lib/es6/belt_HashMapString.js";
import * as RelayRouter__Internal__DeclarationsSupport from "rescript-relay-router/src/RelayRouter__Internal__DeclarationsSupport.mjs";

var loadedRouteRenderers = Belt_HashMapString.make(4);

function make(prepareDisposeTimeoutOpt, param) {
  var prepareDisposeTimeout = prepareDisposeTimeoutOpt !== undefined ? prepareDisposeTimeoutOpt : 300000;
  var match = RelayRouter__Internal__DeclarationsSupport.makePrepareAssets(loadedRouteRenderers, prepareDisposeTimeout);
  var prepareRoute = match.prepareRoute;
  var getPrepared = match.getPrepared;
  var routeName = "Root";
  var loadRouteRenderer = function (param) {
    return RelayRouter__Internal__DeclarationsSupport.doLoadRouteRenderer((function (prim) {
                  return import("@rescriptModule/Root_route_renderer");
                }), routeName, loadedRouteRenderers);
  };
  var makePrepareProps = function (environment, pathParams, queryParams, $$location) {
    return {
            environment: environment,
            location: $$location
          };
  };
  var routeName$1 = "DynamicBroken";
  var loadRouteRenderer$1 = function (param) {
    return RelayRouter__Internal__DeclarationsSupport.doLoadRouteRenderer((function (prim) {
                  return import("@rescriptModule/DynamicBroken_route_renderer");
                }), routeName$1, loadedRouteRenderers);
  };
  var makePrepareProps$1 = function (environment, pathParams, queryParams, $$location) {
    return {
            environment: environment,
            location: $$location,
            item: pathParams["item"]
          };
  };
  var routeName$2 = "Working";
  var loadRouteRenderer$2 = function (param) {
    return RelayRouter__Internal__DeclarationsSupport.doLoadRouteRenderer((function (prim) {
                  return import("@rescriptModule/Working_route_renderer");
                }), routeName$2, loadedRouteRenderers);
  };
  var makePrepareProps$2 = function (environment, pathParams, queryParams, $$location) {
    return {
            environment: environment,
            location: $$location,
            id: pathParams["id"]
          };
  };
  var routeName$3 = "FourOhFour";
  var loadRouteRenderer$3 = function (param) {
    return RelayRouter__Internal__DeclarationsSupport.doLoadRouteRenderer((function (prim) {
                  return import("@rescriptModule/FourOhFour_route_renderer");
                }), routeName$3, loadedRouteRenderers);
  };
  var makePrepareProps$3 = function (environment, pathParams, queryParams, $$location) {
    return {
            environment: environment,
            location: $$location
          };
  };
  return [
          {
            path: "/",
            name: routeName,
            __$rescriptChunkName__: "Root_route_renderer",
            loadRouteRenderer: loadRouteRenderer,
            preloadCode: (function (environment, pathParams, queryParams, $$location) {
                return RelayRouter__Internal__DeclarationsSupport.preloadCode(loadedRouteRenderers, routeName, loadRouteRenderer, makePrepareProps, environment, pathParams, queryParams, $$location);
              }),
            prepare: (function (environment, pathParams, queryParams, $$location, intent) {
                return prepareRoute(environment, pathParams, queryParams, $$location, makePrepareProps, (function (pathParams, queryParams) {
                              return "Root:";
                            }), getPrepared, routeName, loadRouteRenderer, intent);
              }),
            children: []
          },
          {
            path: "dynamic/:item(foo|bar)",
            name: routeName$1,
            __$rescriptChunkName__: "DynamicBroken_route_renderer",
            loadRouteRenderer: loadRouteRenderer$1,
            preloadCode: (function (environment, pathParams, queryParams, $$location) {
                return RelayRouter__Internal__DeclarationsSupport.preloadCode(loadedRouteRenderers, routeName$1, loadRouteRenderer$1, makePrepareProps$1, environment, pathParams, queryParams, $$location);
              }),
            prepare: (function (environment, pathParams, queryParams, $$location, intent) {
                return prepareRoute(environment, pathParams, queryParams, $$location, makePrepareProps$1, (function (pathParams, queryParams) {
                              return "DynamicBroken:" + Belt_Option.getWithDefault(Js_dict.get(pathParams, "item"), "");
                            }), getPrepared, routeName$1, loadRouteRenderer$1, intent);
              }),
            children: []
          },
          {
            path: "working/:id",
            name: routeName$2,
            __$rescriptChunkName__: "Working_route_renderer",
            loadRouteRenderer: loadRouteRenderer$2,
            preloadCode: (function (environment, pathParams, queryParams, $$location) {
                return RelayRouter__Internal__DeclarationsSupport.preloadCode(loadedRouteRenderers, routeName$2, loadRouteRenderer$2, makePrepareProps$2, environment, pathParams, queryParams, $$location);
              }),
            prepare: (function (environment, pathParams, queryParams, $$location, intent) {
                return prepareRoute(environment, pathParams, queryParams, $$location, makePrepareProps$2, (function (pathParams, queryParams) {
                              return "Working:" + Belt_Option.getWithDefault(Js_dict.get(pathParams, "id"), "");
                            }), getPrepared, routeName$2, loadRouteRenderer$2, intent);
              }),
            children: []
          },
          {
            path: "*",
            name: routeName$3,
            __$rescriptChunkName__: "FourOhFour_route_renderer",
            loadRouteRenderer: loadRouteRenderer$3,
            preloadCode: (function (environment, pathParams, queryParams, $$location) {
                return RelayRouter__Internal__DeclarationsSupport.preloadCode(loadedRouteRenderers, routeName$3, loadRouteRenderer$3, makePrepareProps$3, environment, pathParams, queryParams, $$location);
              }),
            prepare: (function (environment, pathParams, queryParams, $$location, intent) {
                return prepareRoute(environment, pathParams, queryParams, $$location, makePrepareProps$3, (function (pathParams, queryParams) {
                              return "FourOhFour:";
                            }), getPrepared, routeName$3, loadRouteRenderer$3, intent);
              }),
            children: []
          }
        ];
}

export {
  make ,
}
/* loadedRouteRenderers Not a pure module */
