// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Router from "./Router.mjs";
import * as RelayEnv from "./RelayEnv.mjs";
import * as RelayRouter from "rescript-relay-router/src/RelayRouter.mjs";
import * as RescriptRelay from "rescript-relay/src/RescriptRelay.mjs";
import * as ReactDOMExperimental from "rescript-relay/src/ReactDOMExperimental.mjs";
import * as RescriptReactErrorBoundary from "@rescript/react/src/RescriptReactErrorBoundary.mjs";

ReactDOMExperimental.renderConcurrentRootAtElementWithId(React.createElement(RescriptRelay.Context.Provider.make, {
          environment: RelayEnv.environment,
          children: React.createElement(RelayRouter.Provider.make, Curry._3(RelayRouter.Provider.makeProps, Router.routerContext, React.createElement(React.Suspense, {
                        children: React.createElement(RescriptReactErrorBoundary.make, {
                              children: React.createElement(RelayRouter.RouteRenderer.make, {
                                    renderPending: (function (pending) {
                                        return React.createElement("div", undefined, pending ? "Loading..." : null);
                                      })
                                  }),
                              fallback: (function (param) {
                                  return "Error!";
                                })
                            }),
                        fallback: "Loading..."
                      }), undefined))
        }), "root");

export {
  
}
/*  Not a pure module */
