// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RelayRouter__Link from "rescript-relay-router/src/RelayRouter__Link.mjs";

function Root(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("p", undefined, React.createElement(RelayRouter__Link.make, {
                      to_: "/dynamic/foo",
                      children: "A broken link"
                    })), React.createElement("p", undefined, React.createElement(RelayRouter__Link.make, {
                      to_: "/working/1",
                      children: "A working link"
                    })));
}

var make = Root;

export {
  make ,
}
/* react Not a pure module */
