// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RelayEnv from "./RelayEnv.mjs";
import * as RelayRouter from "rescript-relay-router/src/RelayRouter.mjs";
import * as RouteDeclarations from "./routes/__generated__/RouteDeclarations.mjs";

var match = RelayRouter.Router.make(RouteDeclarations.make(300000, undefined), RelayRouter.RouterEnvironment.makeBrowserEnvironment(undefined), RelayEnv.environment, (function (priority, param) {
        
      }));

var priority = /* Default */1;

var _cleanup = match[0];

var routerContext = match[1];

export {
  priority ,
  _cleanup ,
  routerContext ,
}
/* match Not a pure module */
